# Generated by Django 6.0.3 on 2026-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
